termination = 'end'.encode()
left_swipe = 'CSL'.encode() # Command Swipe Left (CSL)
right_swipe = 'CSR'.encode() # Command Swipe Right (CSR)
mouse_begin = 'mbegin'.encode()
mouse_end = 'mstop'.encode()
mouse_hold = 'mhold'.encode()
mouse_release = 'mrelease'.encode()
index_tapped = 'itap'.encode()
